### ISSUE TITLE
`Bad file descriptor` when use httpcore to request https site

### ISSUE THREAD

**Issue by Hanaasagi** [encode/httpcore#16]
I found the problem when using `request_async` to request a https site. After reading the code, I think it may a bug of `httpcore`

### Env
- Python 3.7.2
- httpcore 0.2.0

### Steps to reproduce the problem

```Python
import asyncio
import httpcore


async def f():
    ssl = httpcore.SSLConfig(cert=None, verify=False)
    http = httpcore.ConnectionPool(ssl=ssl)
    response = await http.request('GET', 'https://httpbin.org/get')
    print(response.body)


loop = asyncio.get_event_loop()
loop.set_debug(True)
loop.run_until_complete(f())
loop.close()
```

Above code will report

```
Fatal write error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f145cd000b8>
transport: <_SelectorSocketTransport fd=6>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 857, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f145cd000b8>
transport: <_SelectorSocketTransport closing fd=6>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 857, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 676, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 861, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 670, in _fatal_error
    self._force_close(exc)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 682, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 688, in call_soon
    self._check_closed()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

It seems that the socket has already been closed when sending SSL close_notify message.  And when I use python-dbg to run the code, there are some warning

```
sys:1: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.0.2.15', 59830), raddr=('
34.238.32.178', 443)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.7/asyncio/sslproto.py:322: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7f548e936c88>
  source=self)
```

I think when move out coroutine context scope, the socket will auto closed through GC. But `_SSLProtocolTransport` try to send some bytes(`__del__` called after socket closed)

https://github.com/python/cpython/blob/d246a6766b9d8cc625112906299c4cb019944300/Lib/asyncio/sslproto.py#L319

```Python
    def close(self):
        """Close the transport.
        Buffered data will be flushed asynchronously.  No more data
        will be received.  After all buffered data is flushed, the
        protocol's connection_lost() method will (eventually) called
        with None as its argument.
        """
        self._closed = True
        self._ssl_protocol._start_shutdown()

    def __del__(self, _warn=warnings.warn):
        if not self._closed:
            _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
        self.close()
```

But it looks strange, `_SSLProtocolTransport` should still have a reference to the socket, it will not called after socket. I really don't know why, please help me.

**Comment by tomchristie** [comment]
Okay, thanks. Looks like a core python SSL issue to me.
Reduced it down to this example:

```python
import asyncio
import ssl
import certifi


async def f():
    ssl_context = ssl.create_default_context()
    ssl_context.load_verify_locations(cafile=certifi.where())
    await asyncio.open_connection('example.org', 443, ssl=ssl_context)


loop = asyncio.get_event_loop()
loop.run_until_complete(f())
loop.close()
```

Raised as: https://bugs.python.org/issue36709

**Comment by tomchristie** [comment]
A workaround for us would be to fire off a single global task that keeps track of all open connections, and closes them on `asyncio.CancelledError`.

That wouldn't work with `loop.run_until_complete(f()) / loop.close()`, but it would work with `asyncio.run(f())`, since that correctly makes sure to cancel any outstanding tasks.

**Comment by tomchristie** [comment]
Version 0.2.1 will now cleanup keep-alive connection on `ConnectionPool.close()`

I still think there's a valid python bug here, but we can at least make sure to avoid this issue if we cleanup our resources properly. Suggested usages are either:

```python
async with httpcore.ConnectionPool(ssl=ssl) as http:
    response = await http.request('GET', 'https://httpbin.org/get')
```

Or:

```python
http = httpcore.ConnectionPool(ssl=ssl)
response = await http.request('GET', 'https://httpbin.org/get')
http.close()
```

This should also play nicely with `request_async` sessions.

**Comment by Hanaasagi** [comment]
Thank you so much for the feedback!
