### ISSUE TITLE
type error in sync _keepalive_sweep

### ISSUE THREAD

**Issue by aviramha** [encode/httpcore#263]
The usage:
```py
url = httpx.URL(settings.url)
client = httpx.Client(trust_env=False)
executor = ThreadPoolExecutor()
request = {"dada" :3}
executor.submit(self._client.post, self._url.join("cake"), data=request.json())
```
Versions:
* Python 3.7
* Happens using latest httpx (0.16.0), in sync API.
Traceback:
```
Traceback (most recent call last):
  File XXXX
    XXXX
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File XXXX
    XXXXX
  File XXXX
    response = self._client.post(self._url.join(api), data=request.json())
  File "/usr/local/lib/python3.7/site-packages/httpx/_client.py", line 1004, in post
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/httpx/_client.py", line 734, in request
    request, auth=auth, allow_redirects=allow_redirects, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/httpx/_client.py", line 772, in send
    history=[],
  File "/usr/local/lib/python3.7/site-packages/httpx/_client.py", line 809, in _send_handling_auth
    history=history,
  File "/usr/local/lib/python3.7/site-packages/httpx/_client.py", line 837, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.7/site-packages/httpx/_client.py", line 866, in _send_single_request
    ext={"timeout": timeout.as_dict()},
  File "/usr/local/lib/python3.7/site-packages/httpcore/_sync/connection_pool.py", line 199, in request
    self._keepalive_sweep()
  File "/usr/local/lib/python3.7/site-packages/httpcore/_sync/connection_pool.py", line 333, in _keepalive_sweep
    and now >= connection.expires_at
TypeError: '>=' not supported between instances of 'float' and 'NoneType'
```

**Comment by aviramha** [comment]
Could it be due to httpx not being thread safe? ( I haven't seen a negative nor positive statement so I'm not sure if it is or it isn't)

**Comment by florimondmanca** [comment]
Hey, thanks for this!

I've dug up the full condition:

```python

if (
    connection.state == ConnectionState.IDLE
    and connection.expires_at is not None
    and now >= connection.expires_at
            ):
```

So we already do check against `None` just before, which means a thread safety issue is probably to be suspected...

We'd need to analyze the full sequence of events to tell. I think you can get some useful output from running with `HTTPCORE_LOG_LEVEL=trace`. :)

**Comment by florimondmanca** [comment]
@aviramha I wasn't able to reproduce using example.org as a target host, so some extra questions...

- Does it reproduce _without_ the thread pool, ie if sending the request from the main thread?
- What's `settings.url` looking like?
- Is `trust_env=False` relevant to reproducing?

**Comment by florimondmanca** [comment]
Here's an alternative script I'm using to try to reproduce: spawn a bunch of GET requests in threads. The `TypeError` doesn't show even on multiple attempts. Do you get it?

```python
import httpx
from concurrent.futures import ThreadPoolExecutor, as_completed

client = httpx.Client()
with ThreadPoolExecutor() as executor:
    fs = {executor.submit(client.get, "https://example.org") for _ in range(20)}
    for fut in as_completed(fs):
        print(fut.result())  # Prints "<Response [200 OK]>" 20 times as responses come back
```

**Comment by aviramha** [comment]
It happens in production environment and I didn't reproduce it locally... Should httpx.Client be thread safe?

**Comment by tomchristie** [comment]
> Should httpx.Client be thread safe?

Yes. To be more specific, `httpcore` is designed to be thread-safe, so if we can confirm a hole, then that's an error on our side, rather than a usage issue on yours.

**Comment by tomchristie** [comment]
Obsoleted by 0.14
