### ISSUE TITLE
SSLError after upgrading to `0.13.4`

### ISSUE THREAD

**Issue by raphaelts3** [encode/httpcore#361]
After upgrading to `0.13.4` I'm having the following issue in a reasonable amount of my requests:
> SSLError [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2745)

Here is the trace I got from sentry:
```python
  File "my_project/http/asynchronous/__init__.py", line 164, in __aexit__
    await self._client.__aexit__()
  File "httpx/_client.py", line 1890, in __aexit__
    await proxy.__aexit__(exc_type, exc_value, traceback)
  File "httpx/_transports/default.py", line 261, in __aexit__
    await self._pool.__aexit__(exc_type, exc_value, traceback)
  File "httpcore/_async/base.py", line 122, in __aexit__
    await self.aclose()
  File "httpcore/_async/connection_pool.py", line 352, in aclose
    await connection.aclose()
  File "httpcore/_async/connection.py", line 218, in aclose
    await self.connection.aclose()
  File "httpcore/_async/http2.py", line 213, in aclose
    await self.socket.aclose()
  File "httpcore/_backends/anyio.py", line 84, in aclose
    await self.stream.aclose()
  File "anyio/streams/tls.py", line 144, in aclose
    await self.unwrap()
  File "anyio/streams/tls.py", line 136, in unwrap
    await self._call_sslobject_method(self._ssl_object.unwrap)
  File "anyio/streams/tls.py", line 102, in _call_sslobject_method
    result = func(*args)
  File "ssl.py", line 948, in unwrap
    return self._sslobj.shutdown()
```
    
Here is `my_project/http/asynchronous/__init__.py`, line 164:
```python
    async def __aexit__(
        self, _exception_type=None, _exception_value=None, _traceback=None
    ):
>>        await self._client.__aexit__()
        self._in_async_ctx = False
```

**Comment by LanderMoerkerke** [comment]
Same problem over here, Python 3.9

```python
import asyncio

import httpx


async def main():
    async with httpx.AsyncClient() as client:
        out = await client.get(
            "https://webservices-pub.bpost.be/ws/ExternalMailingAddressProofingCSREST_v1/address/autocomplete?q=wetstraat+13+1000+brussel"
        )


if __name__ == "__main__":
    asyncio.run(main())
```

Output
```sh
> python example.py
Traceback (most recent call last):
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/anyio/streams/tls.py", line 102, in _call_sslobject_method
    result = func(*args)
  File "/usr/lib/python3.9/ssl.py", line 888, in read
    v = self._sslobj.read(len)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2633)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 59, in read
    return await self.stream.receive(n)
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/anyio/streams/tls.py", line 152, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/anyio/streams/tls.py", line 121, in _call_sslobject_method
    raise BrokenResourceError from exc
anyio.BrokenResourceError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpx/_transports/default.py", line 61, in map_httpcore_exceptions
    yield
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpx/_transports/default.py", line 201, in __aiter__
    async for part in self._httpcore_stream:
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 57, in __aiter__
    async for chunk in self.stream:
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpcore/_bytestreams.py", line 91, in __aiter__
    async for chunk in self._aiterator:
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpcore/_async/http11.py", line 208, in _receive_response_data
    event = await self._receive_event(timeout)
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpcore/_async/http11.py", line 225, in _receive_event
    data = await self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 63, in read
    raise ReadError from exc
httpcore.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/a/example.py", line 14, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/tmp/a/example.py", line 8, in main
    out = await client.get(
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpx/_client.py", line 1661, in get
    return await self.request(
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpx/_client.py", line 1425, in request
    response = await self.send(
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpx/_client.py", line 1528, in send
    raise exc
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpx/_client.py", line 1519, in send
    await response.aread()
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpx/_models.py", line 1561, in aread
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpx/_models.py", line 1561, in <listcomp>
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpx/_models.py", line 1577, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpx/_models.py", line 1631, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpx/_client.py", line 127, in __aiter__
    async for chunk in self._stream:
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpx/_transports/default.py", line 202, in __aiter__
    yield part
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/lander/.local/share/virtualenvs/a-EouiYCWm/lib/python3.9/site-packages/httpx/_transports/default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError
```

Requirements:
```
httpcore==0.13.4
httpx==0.18.1
```

**Comment by tomchristie** [comment]
First take on this, I'm wondering if this is caused by us failing to use `standard_compatible=False` in the proxy SSL case...

https://github.com/encode/httpcore/blob/de4a3752d12e626486d364f815c718d2c799fb31/httpcore/_backends/anyio.py#L42-L46

(Which we *are* using in the standard case)

https://github.com/encode/httpcore/blob/de4a3752d12e626486d364f815c718d2c799fb31/httpcore/_backends/anyio.py#L151-L156

See the anyio docs on this: https://anyio.readthedocs.io/en/stable/streams.html?highlight=ssl#dealing-with-ragged-eofs

**Comment by tomchristie** [comment]
This is also prompting me to wonder why we're not yet using [Trio's equivalent flag `https_compatible=True`](https://trio.readthedocs.io/en/stable/reference-io.html?highlight=ssl#trio.SSLStream), in [our `trio` backend](https://github.com/encode/httpcore/blob/master/httpcore/_backends/trio.py). Surprising that no-one has reported bumping into any issues there.

**Comment by tomchristie** [comment]
Relevant part of anyio... https://github.com/agronholm/anyio/blob/99ec00e67c533d4b12d2a2aff8cb6aa2b0f0344f/src/anyio/streams/tls.py#L129-L149

**Comment by tomchristie** [comment]
Righty, so the traceback includes this...

```python
  File "anyio/streams/tls.py", line 144, in aclose
    await self.unwrap()
```

Which [is this line here](https://github.com/agronholm/anyio/blob/99ec00e67c533d4b12d2a2aff8cb6aa2b0f0344f/src/anyio/streams/tls.py#L144).

```python
    async def aclose(self) -> None:
        if self.standard_compatible:
            try:
                await self.unwrap()  # <--- Here
            except BaseException:
                await aclose_forcefully(self.transport_stream)
                raise


        await self.transport_stream.aclose()
```

Which, yup, implies that `standard_compatible` has not been set to `False` in this case (which it should, because HTTPS implementations may drop the TLS EOFs.)
