### ISSUE TITLE
High workload issue "partially initialized module 'anyio._backends._asyncio' has no attribute 'checkpoint_if_cancelled'"

### ISSUE THREAD

**Issue by jjsaunier** [encode/httpcore#395]
Hey,

I notice some error are thrown sporadically with no reason

```
 core.error_handler:log_error:18 - <class 'AttributeError'> - AttributeError("partially initialized module 'anyio._backends._asyncio' has no attribute 'checkpoint_if_cancelled' (most likely due to a circular import)") 
 ```
 
 Full stack trace
 
 ```
 File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1568, in send
  response = await self._send_handling_auth(
File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1604, in _send_handling_auth
  response = await self._send_handling_redirects(
File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1640, in _send_handling_redirects
  response = await self._send_single_request(request, timeout)
File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1681, in _send_single_request
  ) = await transport.handle_async_request(
File "/usr/local/lib/python3.9/site-packages/httpx_socks/_async_transport.py", line 60, in handle_async_request
  response = await connection.handle_async_request(
File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 128, in handle_async_request
  async with self.request_lock:
File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/base.py", line 76, in __aenter__
  await self.acquire()
File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 104, in acquire
  await self._lock.acquire()
File "/usr/local/lib/python3.9/site-packages/anyio/_core/_synchronization.py", line 117, in acquire
  await checkpoint_if_cancelled()
File "/usr/local/lib/python3.9/site-packages/anyio/lowlevel.py", line 42, in checkpoint_if_cancelled
  await get_asynclib().checkpoint_if_cancelled()
 ```
 
Env:  Linux : `5.4.0-80-generic` - Running in k8s
Python interpreter : `Python 3.9.5` 

Dependencies : 

```
hpack==4.0.0
httpcore==0.13.6
httptools==0.2.0
httpx==0.18.2
httpx-socks==0.4.1
hyperframe==6.0.1
h11==0.12.0
h2==4.0.0
```

Did someone already experience the same issue ? My project is using `asyncio` package as async lib, so nothing exoctic here. The `send` method is called in a multi threaded app. 

Thanks, will continue to dig on my side what happened

**Comment by DanSava** [comment]
Hi, 

I encountered a similar error `AttributeError: module 'anyio._backends._asyncio' has no attribute 'current_time' ` 

Full-stack trace:

```
    resp = await session.post(url=url, headers=headers, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/httpx/_client.py", line 1837, in post
    timeout=timeout,
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/httpx/_client.py", line 1495, in request
    request, auth=auth, allow_redirects=allow_redirects, timeout=timeout
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/httpx/_client.py", line 1591, in send
    history=[],
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/httpx/_client.py", line 1620, in _send_handling_auth
    history=history,
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/httpx/_client.py", line 1655, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/httpx/_client.py", line 1704, in _send_single_request
    extensions={"timeout": timeout.as_dict()},
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/httpx/_transports/default.py", line 286, in handle_async_request
    extensions=extensions,
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/httpcore/_async/connection_pool.py", line 218, in handle_async_request
    await self._keepalive_sweep()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/httpcore/_async/connection_pool.py", line 303, in _keepalive_sweep
    now = await self._backend.time()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/httpcore/_backends/auto.py", line 64, in time
    return await self.backend.time()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/httpcore/_backends/anyio.py", line 198, in time
    return float(anyio.current_time())
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/anyio/_core/_eventloop.py", line 105, in current_time
    return DeprecatedAwaitableFloat(get_asynclib().current_time(), current_time)
AttributeError: module 'anyio._backends._asyncio' has no attribute 'current_time' 
```

The project is also using `asyncio` and `httpx` and the requests are called from a multi-threaded application

**Comment by 2-X** [comment]
getting the same issue. anyone have any luck resolving this? http/2 is a requirement for my application

**Comment by tomchristie** [comment]
Which version of `anyio` do you folks have installed?

**Comment by 2-X** [comment]
@tomchristie version `3.3.2`
```
Name: anyio
Version: 3.3.2
Summary: High level compatibility layer for multiple asynchronous event loop implementations
Home-page: UNKNOWN
Author: Alex Grönholm
Author-email: alex.gronholm@nextday.fi
License: MIT
Location: /home/kris/.local/lib/python3.8/site-packages
Requires: idna, sniffio
Required-by: httpcore
```

**Comment by tomchristie** [comment]
Okay, so first up, let's not confuse two different issues here. The traceback @DanSava mentions doesn't appear to me to be related to the opening issue here, so let's treat that separately.

@jjsaunier, @2-X - Are either of you able to reduce this issue down to a simple script that demostrates the issue occurring?

This thread against the anyio repo. looks relevant... https://github.com/agronholm/anyio/issues/210 - particularly because it mentions multithreading. @jjsaunier I'm confused by your mention of "The send method is called in a multi threaded app." - if you're using async, you ought to be using async tasks for concurrency, rather than multiple threads.

**Comment by jjsaunier** [comment]
@tomchristie very hard to reproduce on my side, sporadic, with high load seems to be the factor and mostly test and learn in production. Currently fine-tuning the number of threads has positive feedback. Might be a hint. Since I tuned it, never get the error again. 

For async and multithread yes, I isolate loop and use `asyncio.run_coroutine_threadsafe` to schedule on main thread from children - it spawns on-demand thread and avoids side effects on other running stuff if it goes bad. Httpx calls are made from children with the child loop

**Comment by tomchristie** [comment]
Given eg. agronholm/anyio#210 is now closed, and also give the significant reworking of httpcore for version 0.14 I'm going to close this off for now, until/unless we get any re-reports.

**Comment by shughes-uk** [comment]
We're seeing this pop up again. We're using django + async views served via uvicorn. Django currently will use a thread per request (resulting in multiple asyncio loops) if you have any sync middleware installed. 

httpcore: 0.17.2
anyio: 3.6.2
python: 3.9.16

Snipped our part of the code out of this traceback and just included everything starting with httpx

```
  File "/opt/coiled/env/lib/python3.9/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/opt/coiled/env/lib/python3.9/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/opt/coiled/env/lib/python3.9/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/opt/coiled/env/lib/python3.9/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/opt/coiled/env/lib/python3.9/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/opt/coiled/env/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/opt/coiled/env/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 224, in handle_async_request
    async with self._pool_lock:
  File "/opt/coiled/env/lib/python3.9/site-packages/httpcore/_synchronization.py", line 53, in __aenter__
    await self._anyio_lock.acquire()
  File "/opt/coiled/env/lib/python3.9/site-packages/anyio/_core/_synchronization.py", line 121, in acquire
    await checkpoint_if_cancelled()
  File "/opt/coiled/env/lib/python3.9/site-packages/anyio/lowlevel.py", line 42, in checkpoint_if_cancelled
    await get_asynclib().checkpoint_if_cancelled()
AttributeError: partially initialized module 'anyio._backends._asyncio' has no attribute 'checkpoint_if_cancelled' (most likely due to a circular import)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/coiled/env/lib/python3.9/site-packages/httpx/_client.py", line 2003, in __aexit__
    await self._transport.__aexit__(exc_type, exc_value, traceback)
  File "/opt/coiled/env/lib/python3.9/site-packages/httpx/_transports/default.py", line 332, in __aexit__
    await self._pool.__aexit__(exc_type, exc_value, traceback)
  File "/opt/coiled/env/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 326, in __aexit__
    await self.aclose()
  File "/opt/coiled/env/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 311, in aclose
    async with self._pool_lock:
  File "/opt/coiled/env/lib/python3.9/site-packages/httpcore/_synchronization.py", line 53, in __aenter__
    await self._anyio_lock.acquire()
  File "/opt/coiled/env/lib/python3.9/site-packages/anyio/_core/_synchronization.py", line 121, in acquire
    await checkpoint_if_cancelled()
  File "/opt/coiled/env/lib/python3.9/site-packages/anyio/lowlevel.py", line 42, in checkpoint_if_cancelled
    await get_asynclib().checkpoint_if_cancelled()
AttributeError: partially initialized module 'anyio._backends._asyncio' has no attribute 'checkpoint_if_cancelled' (most likely due to a circular import)
```
