### ISSUE TITLE
httpx.ReadError on reading HTTPS webpage with valid certificate

### ISSUE THREAD

**Issue by devl00p** [encode/httpcore#396]
I spotted this error that may appear even if the website certificate is valid.

Code to reproduce:

```python
import asyncio
import httpx

async def main():
    async with httpx.AsyncClient() as client:
        response = await client.get("https://etendering.ted.europa.eu/cft/cft-search.html")
        print(response.text[-50:])

asyncio.run(main())
```

Generated traceback:

```
Traceback (most recent call last):
  File "/tmp/testenv/lib64/python3.8/site-packages/anyio/streams/tls.py", line 102, in _call_sslobject_method
    result = func(*args)
  File "/usr/lib64/python3.8/ssl.py", line 888, in read
    v = self._sslobj.read(len)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2635)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/testenv/lib64/python3.8/site-packages/httpcore/_backends/anyio.py", line 60, in read
    return await self.stream.receive(n)
  File "/tmp/testenv/lib64/python3.8/site-packages/anyio/streams/tls.py", line 152, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "/tmp/testenv/lib64/python3.8/site-packages/anyio/streams/tls.py", line 121, in _call_sslobject_method
    raise BrokenResourceError from exc
anyio.BrokenResourceError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/testenv/lib64/python3.8/site-packages/httpx/_transports/default.py", line 61, in map_httpcore_exceptions
    yield
  File "/tmp/testenv/lib64/python3.8/site-packages/httpx/_transports/default.py", line 202, in __aiter__
    async for part in self._httpcore_stream:
  File "/tmp/testenv/lib64/python3.8/site-packages/httpcore/_async/connection_pool.py", line 57, in __aiter__
    async for chunk in self.stream:
  File "/tmp/testenv/lib64/python3.8/site-packages/httpcore/_bytestreams.py", line 91, in __aiter__
    async for chunk in self._aiterator:
  File "/tmp/testenv/lib64/python3.8/site-packages/httpcore/_async/http11.py", line 208, in _receive_response_data
    event = await self._receive_event(timeout)
  File "/tmp/testenv/lib64/python3.8/site-packages/httpcore/_async/http11.py", line 225, in _receive_event
    data = await self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/tmp/testenv/lib64/python3.8/site-packages/httpcore/_backends/anyio.py", line 65, in read
    raise ReadError from exc
httpcore.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/test.py", line 9, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/tmp/test.py", line 6, in main
    response = await client.get("https://etendering.ted.europa.eu/cft/cft-search.html")
  File "/tmp/testenv/lib64/python3.8/site-packages/httpx/_client.py", line 1740, in get
    return await self.request(
  File "/tmp/testenv/lib64/python3.8/site-packages/httpx/_client.py", line 1494, in request
    response = await self.send(
  File "/tmp/testenv/lib64/python3.8/site-packages/httpx/_client.py", line 1601, in send
    raise exc
  File "/tmp/testenv/lib64/python3.8/site-packages/httpx/_client.py", line 1595, in send
    await response.aread()
  File "/tmp/testenv/lib64/python3.8/site-packages/httpx/_models.py", line 1579, in aread
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "/tmp/testenv/lib64/python3.8/site-packages/httpx/_models.py", line 1579, in <listcomp>
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "/tmp/testenv/lib64/python3.8/site-packages/httpx/_models.py", line 1595, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/tmp/testenv/lib64/python3.8/site-packages/httpx/_models.py", line 1649, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/tmp/testenv/lib64/python3.8/site-packages/httpx/_client.py", line 150, in __aiter__
    async for chunk in self._stream:
  File "/tmp/testenv/lib64/python3.8/site-packages/httpx/_transports/default.py", line 203, in __aiter__
    yield part
  File "/usr/lib64/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmp/testenv/lib64/python3.8/site-packages/httpx/_transports/default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError
```

We can see that `anyio` caught a `ssl.SSLEOFError` error and generated a `BrokenResourceError` exception.

It was caught by httpcore which generated a `httpcore.ReadError` exception (see https://github.com/encode/httpcore/blob/8970484a78e5eadeee09580d3e35f99023014271/httpcore/_backends/anyio.py#L64 )

Just below there is a caught for `EndOfStream` that will just return an empty byte string.

Dealing with the `BrokenResourceError` exception in the same exact way than for `EndOfStream` (returning empty byte string) seems to solve the problem.

Proposed change:

```python
    async def read(self, n: int, timeout: TimeoutDict) -> bytes:                                                       
        read_timeout = timeout.get("read")                                                                             
        async with self.read_lock:                                                                                     
            try:                                                                                                       
                with anyio.fail_after(read_timeout):                                                                   
                    return await self.stream.receive(n)                                                                
            except TimeoutError:                                                                                       
                await self.stream.aclose()                                                                             
                raise ReadTimeout from None                                                                            
            except (EndOfStream, BrokenResourceError):   # return empty byte instead of raising ReadError                                                            
                return b""                                                                                             
```

Versions used:

```
anyio==3.3.0
async-generator==1.10
attrs==21.2.0
certifi==2021.5.30
charset-normalizer==2.0.4
h11==0.12.0
httpcore==0.13.6
httpx==0.19.0
idna==3.2
outcome==1.1.0
rfc3986==1.5.0
sniffio==1.2.0
sortedcontainers==2.4.0
```

with python 3.8.11

Regards

**Comment by tomchristie** [comment]
Updating to the latest version of anyio should now resolve this. 👍

Thanks for the report. 😊
