### ISSUE TITLE
ImportError with httpcore 0.14 without h2

### ISSUE THREAD

**Issue by shadchin** [encode/httpcore#426]
Example
```
$ pip install httpcore certifi
$ python
Python 3.9.7 (default, Sep  9 2021, 23:20:13)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import httpcore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shadchin/.local/lib/python3.9/site-packages/httpcore/__init__.py", line 2, in <module>
    from ._async import (
ImportError: cannot import name 'AsyncHTTP2Connection' from 'httpcore._async' (/home/shadchin/.local/lib/python3.9/site-packages/httpcore/_async/__init__.py)
>>>
```

`certifi` need too
```
$ pip install httpcore
$ python
Python 3.9.7 (default, Sep  9 2021, 23:20:13)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import httpcore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shadchin/.local/lib/python3.9/site-packages/httpcore/__init__.py", line 1, in <module>
    from ._api import request, stream
  File "/home/shadchin/.local/lib/python3.9/site-packages/httpcore/_api.py", line 5, in <module>
    from ._sync.connection_pool import ConnectionPool
  File "/home/shadchin/.local/lib/python3.9/site-packages/httpcore/_sync/__init__.py", line 1, in <module>
    from .connection import HTTPConnection
  File "/home/shadchin/.local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 8, in <module>
    from .._ssl import default_ssl_context
  File "/home/shadchin/.local/lib/python3.9/site-packages/httpcore/_ssl.py", line 3, in <module>
    import certifi
ModuleNotFoundError: No module named 'certifi'
>>>
```

**Comment by tomchristie** [comment]
Great thanks. Resolved in #428 - I'll get onto rolling a new release shortly.
